# Copyright (c) 2020 Nanjing Xiaoxiongpai Intelligent Technology Co., Ltd.
# 智慧路灯项目 — 合并 sample（基于 C3 + D5）

static_library("streetlight_mqtt") {
    sources = [
        "streetlight_mqtt.c",
        "src/E53_SC1.c",
        "src/wifi_connect.c",
    ]

    cflags = [ "-Wno-unused-variable" ]
    cflags += [ "-Wno-unused-but-set-variable" ]
    include_dirs = [
        "//utils/native/lite/include",
        "//kernel/liteos_m/components/cmsis/2.0",
        "//base/iot_hardware/interfaces/kits/wifiiot_lite",
        "//foundation/communication/interfaces/kits/wifi_lite/wifiservice",
        "//vendor/hisi/hi3861/hi3861/third_party/lwip_sack/include/",
        "//third_party/paho_mqtt/MQTTPacket/src",
        "//third_party/paho_mqtt/MQTTClient-C/src",
        "include",
        ".",
    ]
    deps = [
        "//third_party/paho_mqtt:pahomqtt_static",
    ]
}
